### ISSUE TITLE
Adjustment to cjs format

### ISSUE THREAD

**Issue by guybedford** [jrauschenbusch/babel-plugin-transform-cjs-system-wrapper#6]
I've just made the following adjustment to the CJS output (https://github.com/systemjs/builder/commit/7a3ddbf7c9c327dea5b35e209ff5589b42cd670b):

```javascript
var define, global = this || self, GLOBAL = global;
```

The reason for this is this bug in Safari web workers - https://bugs.webkit.org/show_bug.cgi?id=119472.

**Comment by jrauschenbusch** [comment]
Fixed with https://github.com/jrauschenbusch/babel-plugin-transform-cjs-system-wrapper/commit/7362c3a8d91895606a6f8268327089e94191df68

**Comment by guybedford** [comment]
Excellent, thank you!
